apiVersion: apps/v1
kind: Deployment
metadata:
  name: catnip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catnip-app
      version: blue
  template:
    metadata:
      name: 
      labels:
        app: catnip-pod
        version: blue
    spec:
      containers:
      - name: catnip-container
        image: dockermaty1997/catnip:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: catnip-svc
  labels:
    app: catnip-app
spec:
  selector:
    app: catnip-app
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80